In [84]:
# Importer les packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [85]:
# gérer les warnings
import warnings
warnings.filterwarnings("ignore")

### <font color = 'bisque'> Importer et lire les données

In [86]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [87]:
# Importer les données
df = pd.read_csv('/content/drive/MyDrive/karaguaIA/Supervised Learning /Classification/Doc 1/Car_Data.csv')

Les données ont été scrapées de la page https://www.expat-dakar.com/voitures/dakar. Ce sont des données de vehicules en vente à Dakar.
L'objectif de ce TP est de mettre en place un modèle classification qui en partant de certaines caractéristiques d'une voiture nous prédira si celle-ci est venante ou d'occassion.

In [88]:
# Afficher les données
df.head()

       Marque  Année Boite_Vitesse           Adresse      Prix Venant_Occasion
0  Mitsubishi   2017   Automatique   Liberte 6,Dakar   9750000          Venant
1        Ford   2009      Manuelle        Yoff,Dakar   2500000      D'occasion
2         BMW   2015   Automatique  Cité Damel,Dakar  15500000      D'occasion
3        Ford   2013   Automatique    Almadies,Dakar   3800000      D'occasion
4         GMC   2014   Automatique         Hlm,Dakar   7500000          Venant

In [89]:
# Afficher la dimension des données
df.shape

(5507, 6)

In [90]:
# Infos des données
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5507 entries, 0 to 5506
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Marque           5507 non-null   object
 1   Année            5507 non-null   int64
 2   Boite_Vitesse    5507 non-null   object
 3   Adresse          5507 non-null   object
 4   Prix             5507 non-null   int64
 5   Venant_Occasion  5507 non-null   object
dtypes: int64(2), object(4)
memory usage: 258.3+ KB

In [91]:
# Décrire les données
df.describe(include = 'number').T
# df.describe(include = 'object').T

,count,mean,std,min,25%,50%,75%,max
Année,5507.0,2.014508e+03,3.089839e+00,1990.0,2013.0,2015.0,2016.0,2024.0
Prix,5507.0,1.110512e+07,1.619639e+07,1.0,4600000.0,7800000.0,12500000.0,779414131.0

### <font color = 'bisque'> Préparation des données

In [92]:
# splitter la variable Adresse en Quartier et Region
df[['Quartier', 'Region']] =df.Adresse.str.split(',', n = 1, expand = True)
df.head()

,Marque,Année,Boite_Vitesse,Adresse,Prix,Venant_Occasion,Quartier,Region
0,Mitsubishi,2017,Automatique,"Liberte 6,Dakar",9750000,Venant,Liberte 6,Dakar
1,Ford,2009,Manuelle,"Yoff,Dakar",2500000,D'occasion,Yoff,Dakar
2,BMW,2015,Automatique,"Cité Damel,Dakar",15500000,D'occasion,Cité Damel,Dakar
3,Ford,2013,Automatique,"Almadies,Dakar",3800000,D'occasion,Almadies,Dakar
4,GMC,2014,Automatique,"Hlm,Dakar",7500000,Venant,Hlm,Dakar

In [93]:
# Supprimer les variable Adresse et Region
df.drop(['Adresse', 'Region'],axis = 1, inplace = True)
# df = df.drop(['Adresse', 'Region'],axis = 1)
df.head()

       Marque  Année Boite_Vitesse      Prix Venant_Occasion    Quartier
0  Mitsubishi   2017   Automatique   9750000          Venant   Liberte 6
1        Ford   2009      Manuelle   2500000      D'occasion        Yoff
2         BMW   2015   Automatique  15500000      D'occasion  Cité Damel
3        Ford   2013   Automatique   3800000      D'occasion    Almadies
4         GMC   2014   Automatique   7500000          Venant         Hlm

In [94]:
# Gérer les espaces sur la variable quartier
df.Quartier = df.Quartier.str.strip()
df.Quartier.unique()

array(['Liberte 6', 'Yoff', 'Cité Damel', 'Almadies', 'Hlm', 'VDN',
       'Plateau', 'Parcelles Assainies', 'Liberte 6 extension',
       'Colobane', 'Sicap foire', 'Fenêtre mermoz', 'Golf', 'Rufisque',
       'Nord foire', 'Ouest foire', 'Sacré-cœur', 'Sicap Liberté',
       'Hann maristes', 'Mbao', 'Gueule-Tapée', 'Amitié', 'Guediawaye',
       'Mermoz', 'Mamelles', 'Pikine', 'Cité keur gorgui', 'Grand-Yoff',
       'Grand-Dakar', 'Fann', 'Keur Massar', 'Hlm grand-yoff',
       'Avenue Bourguiba', 'Castor', 'Médina', 'Patte d‘oie', 'Dieuppeul',
       'Zac Mbao', 'Cambérène', 'Hann Bel-Air', 'Cité biagui', 'Dalifort',
       'Ngor', 'Point-e', 'Liberte 5', 'Bargny', 'Comico', 'Almadies 2',
       'Biscuiterie', 'Sud foire', 'Gibraltar', 'Diamaguene', 'Malika',
       'Tivaouane peulh', 'Bel air', 'Zone de captage', 'Djily mbaye',
       'Sicap Sacré-cœur', 'Yeumbeul', 'Ouakam', 'Liberte 2', 'Virage',
       'Thiaroye', 'Sebikotane', 'Niague', 'Sangalkam', 'Sicap mbao',
       'Liberte 1', 'Ndiakhirate', 'Diamniadio', 'Cite Mixta',
       'Cité assemblée', 'Sicap baobab', 'Bambilor', 'Hann marinas',
       'Keur ndiaye lô', 'Derkle', 'Liberte 4', 'Gorée', 'Cité avion',
       'Yene', 'Lac rose', 'Lac Rose', 'Cité asecna', 'Fann Hock',
       'Liberte 3'], dtype=object)

In [95]:
# renommer les variables
df.rename(columns= {'Boite_Vitesse': 'Transmission',
                    'Venant_Occasion': 'Etat'

}, inplace = True)
df.head()

       Marque  Année Transmission      Prix        Etat    Quartier
0  Mitsubishi   2017  Automatique   9750000      Venant   Liberte 6
1        Ford   2009     Manuelle   2500000  D'occasion        Yoff
2         BMW   2015  Automatique  15500000  D'occasion  Cité Damel
3        Ford   2013  Automatique   3800000  D'occasion    Almadies
4         GMC   2014  Automatique   7500000      Venant         Hlm

In [96]:
# Réorganiser les variables
df= df[["Marque","Année", "Transmission", "Quartier", "Prix",	"Etat"]]
df.head()

       Marque  Année Transmission    Quartier      Prix        Etat
0  Mitsubishi   2017  Automatique   Liberte 6   9750000      Venant
1        Ford   2009     Manuelle        Yoff   2500000  D'occasion
2         BMW   2015  Automatique  Cité Damel  15500000  D'occasion
3        Ford   2013  Automatique    Almadies   3800000  D'occasion
4         GMC   2014  Automatique         Hlm   7500000      Venant

In [97]:
# Les valeurs uniques de la variable Etat
np.unique(df.Etat)

array(["D'occasion", 'Venant'], dtype=object)

In [98]:
# Les valeurs uniques de la variable Marque
np.unique(df.Marque)[:5]

array(['Acura', 'Audi', 'Autres', 'BMW', 'Buick'], dtype=object)

In [99]:
# Les valeurs uniques de la variable Quartier
np.unique(df.Quartier)[:5]

array(['Almadies', 'Almadies 2', 'Amitié', 'Avenue Bourguiba', 'Bambilor'],
      dtype=object)

In [100]:
# Les valeurs uniques de la variable transmission
np.unique(df.Transmission)

array(['Automatique', 'Manuelle', 'Tiptronic'], dtype=object)

In [101]:
# Importer le modèle LabelEncoder
from sklearn.preprocessing import LabelEncoder
# Encoder les variables catégorielles
encoder = LabelEncoder()
# encoder les variables
for colname in df.select_dtypes(include = 'object').columns:
  df[colname] = encoder.fit_transform(df[colname])

df.head()

   Marque  Année  Transmission  Quartier      Prix  Etat
0      30   2017             0        49   9750000     1
1      13   2009             1        83   2500000     0
2       3   2015             0        11  15500000     0
3      13   2013             0         0   3800000     0
4      14   2014             0        38   7500000     1

In [102]:
# Nombre d'observations dans chaque classe de la variable cible
val = df.Etat.value_counts()
val

Etat
1    2855
0    2652
Name: count, dtype: int64

In [103]:
# Diagramme en bar du nombre d'observations dans chaque classe de la variable cible
import plotly.express as px
fig = px.bar(x = val.index, y = val.values, color = val.index.astype('str'), text_auto=True)
fig.show()

In [104]:
# Fractionner les données en X (Variables prédicteurs) et y (Variable cible)
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
x[:5], y[:5]

(array([[      30,     2017,        0,       49,  9750000],
        [      13,     2009,        1,       83,  2500000],
        [       3,     2015,        0,       11, 15500000],
        [      13,     2013,        0,        0,  3800000],
        [      14,     2014,        0,       38,  7500000]]),
 array([1, 0, 0, 0, 1]))

In [105]:
# Importer MinMaxScaler
from sklearn.preprocessing import MinMaxScaler # x = (x -x_min) /(x_max - x_min)
# objet MinMax
scaler = MinMaxScaler()
x = scaler.fit_transform(x)
x[:5]

array([[0.66666667, 0.79411765, 0.        , 0.57647059, 0.01250939],
       [0.28888889, 0.55882353, 0.5       , 0.97647059, 0.00320754],
       [0.06666667, 0.73529412, 0.        , 0.12941176, 0.01988673],
       [0.28888889, 0.67647059, 0.        , 0.        , 0.00487546],
       [0.31111111, 0.70588235, 0.        , 0.44705882, 0.00962261]])

In [106]:
# Splitter les données
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size = 0.2, random_state= 42)

In [107]:
# Afficher les dimensions X_train, y_train
x_train[:5], y_train[:5]
x_train.shape, y_train.shape

((4405, 5), (4405,))

In [108]:
# Afficher les dimensions X_test, y_test
x_test[:5], y_test[:5]
x_test.shape, y_test.shape

((1102, 5), (1102,))

### <font color = 'bisque'> Modélisation

#### <font color = 'teal'>K nearest neighbor (K-NN)

#### <font color = 'teal'> Fonctionnement mathématique du K-NN

Le **K plus proches voisins (K-Nearest Neighbors)** est un algorithme d'apprentissage supervisé **non paramétrique** et **paresseux** (*lazy learning*) : il ne construit aucune fonction/modèle explicite pendant l'entraînement, il se contente de **mémoriser** l'ensemble des données d'entraînement $(x_i, y_i)$. Tout le calcul se fait au moment de la prédiction.

**1. Principe général**

Pour prédire la classe d'une nouvelle observation $x$ :
1. On calcule la distance entre $x$ et **tous** les points $x_i$ de l'ensemble d'entraînement.
2. On sélectionne les $k$ points les plus proches de $x$ (les "$k$ voisins").
3. On attribue à $x$ la classe **majoritaire** parmi ces $k$ voisins (vote majoritaire).

**2. Mesure de distance**

La distance la plus utilisée (et celle utilisée par défaut dans `KNeighborsClassifier`) est la **distance euclidienne**. Pour deux observations $x = (x^{(1)}, x^{(2)}, ..., x^{(p)})$ et $x_i = (x_i^{(1)}, x_i^{(2)}, ..., x_i^{(p)})$ décrites par $p$ variables :

$$d(x, x_i) = \sqrt{\sum_{j=1}^{p} \left(x^{(j)} - x_i^{(j)}\right)^2}$$

D'autres distances existent (paramètre `p` de Minkowski) :
- **Manhattan** ($p=1$) : $d(x, x_i) = \sum_{j=1}^{p} \left| x^{(j)} - x_i^{(j)} \right|$
- **Minkowski (générale)** : $d(x, x_i) = \left( \sum_{j=1}^{p} \left| x^{(j)} - x_i^{(j)} \right|^q \right)^{1/q}$, l'Euclidienne étant le cas $q=2$.

⚠️ C'est précisément pour que cette distance ait un sens (et que les variables avec de grandes échelles, comme `Prix`, ne dominent pas les autres) qu'on a **normalisé** les variables avec `MinMaxScaler` avant d'entraîner le modèle.

**3. Règle de décision (classification)**

Soit $N_k(x)$ l'ensemble des $k$ voisins les plus proches de $x$. La classe prédite $\hat{y}$ est celle qui maximise la probabilité *a posteriori* estimée par le vote majoritaire :

$$\hat{y} = \underset{c}{\text{argmax}} \sum_{i \in N_k(x)} \mathbb{1}(y_i = c)$$

où $\mathbb{1}(y_i = c)$ vaut $1$ si le voisin $i$ appartient à la classe $c$, et $0$ sinon. Dans notre cas binaire ($c \in \{0 : \text{D'occasion},\ 1 : \text{Venant}\}$), on compte simplement combien de voisins sont dans chaque classe et on choisit la classe majoritaire.

On peut aussi utiliser un **vote pondéré** (`weights = 'distance'`), où chaque voisin pèse d'autant plus qu'il est proche :

$$w_i = \frac{1}{d(x, x_i)}$$

**4. Choix du nombre de voisins $k$**

$k$ est un **hyperparamètre** clé :
- $k$ trop petit → modèle très sensible au bruit (overfitting), frontière de décision très irrégulière.
- $k$ trop grand → modèle trop lisse, risque de sous-apprentissage (underfitting), et les classes minoritaires sont noyées.

C'est pourquoi on utilise ci-dessous une **validation croisée** (`GridSearchCV`, $cv=5$) pour tester $k \in \{2, ..., 30\}$ et choisir la valeur qui maximise l'accuracy moyenne sur les 5 plis.

**5. Complexité**

Comme il n'y a pas d'entraînement à proprement parler, la prédiction pour une seule observation coûte $O(n \times p)$ (calcul de $n$ distances sur $p$ variables), $n$ étant le nombre d'observations d'entraînement : c'est pour cela que le K-NN peut devenir lent sur de grands jeux de données.

In [109]:
# Importer KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [114]:
# importer GridSearchCV
from sklearn.model_selection import GridSearchCV
# initialiser le modèle knn
knn = KNeighborsClassifier()
# choisir une rangée de valeurs variante de 2 à 30
k_list = list(range(2,31))
# créer le dictionnaire params
params = {'n_neighbors' : k_list}
# Instantier le modèle GridSearchCV
grid = GridSearchCV(knn, params, cv = 5)

# lancer la recherche
grid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
                                         14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
                                         24, 25, 26, 27, 28, 29, 30]})

In [117]:
# k optimal
k = grid.best_params_['n_neighbors']
# Instantier le modèle
knn_modele = KNeighborsClassifier(n_neighbors = k)
# Entrainer le modèle
knn_modele.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=23)

### <font color = 'bisque'> Prédiction

In [127]:
#un echantilon de 10 observations sur les donnees
x_test_10 = x_test[10:20]
y_test_10 = y_test[10:20]
# pour la prediction
y_predict_10 = knn_modele.predict(x_test_10)
class_names = ['Ocasion', 'venant']

# afficher les predictions
for i in range(10):
  print(f'prediction {str(i+1)} : {class_names[y_predict_10[i]]} | Reel {str(i+1)} {class_names[y_test_10[i]]}')

prediction 1 : venant | Reel 1 venant
prediction 2 : venant | Reel 2 Ocasion
prediction 3 : venant | Reel 3 venant
prediction 4 : Ocasion | Reel 4 Ocasion
prediction 5 : venant | Reel 5 venant
prediction 6 : Ocasion | Reel 6 Ocasion
prediction 7 : venant | Reel 7 venant
prediction 8 : venant | Reel 8 venant
prediction 9 : Ocasion | Reel 9 Ocasion
prediction 10 : Ocasion | Reel 10 venant

### <font color = 'bisque'> Evaluation

In [132]:
# Importer accuracy_score
from sklearn.metrics import accuracy_score
y_pred = knn_modele.predict(x_test)
acc_knn = accuracy_score(y_test, y_pred)
# affichage de l'accuracy
print(f'Accuracy du models : {acc_knn: .2f}')

Accuracy du models :  0.78

In [113]:
# Prédire les labels des données test